on:
  workflow_dispatch:


name: get parliament stats


jobs:
  get-stats:
    # Use Ubuntu   
    runs-on: ubuntu-latest 
    steps:
       # Install R
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2  
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: get_stats  
        # Code to execute R script
        run: Rscript scripts/get_parliament_stats.R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
